#define LIDAR_MIN_X_RADIUS     -6000 
#define LIDAR_MAX_X_RADIUS     6000 
#define LIDAR_MAX_Y_RADIUS     2500
#define LIDAR_BLOB_ROWS        20U
#define LIDAR_BLOB_COLUMNS     180U 
#define LIDAR_BLOB_ROW_RESOLUTION    (LIDAR_MAX_Y_RADIUS/LIDAR_BLOB_ROWS)    
#define LIDAR_BLOB_COLUMN_RESOLUTION (2*LIDAR_MAX_X_RADIUS/LIDAR_BLOB_COLUMNS)  